# Default values for authorizer.
replicaCount: 1
image:
  repository: ghcr.io/dzeromsk/ingress-saml-authorizer
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  type: ClusterIP
  port: 80
secret:
  create: true
config:
  create: true
  url: "http://localhost"
  keyfile: "/etc/authorizer/cert/tls.key"
  certificatefile: "/etc/authorizer/cert/tls.crt"
  allowidpinitiated: false
  idpmetadataurl: "https://samltest.id/saml/idp"
  signrequest: true # some IdP require the SLO request to be signed
  addr: ":8000"
