{{- if .Values.secret.create -}}
{{- $cert := genSelfSignedCert "ingress-saml-authorizer" nil nil 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authorizer.secretName" . }}
  labels:
    {{- include "authorizer.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
